source 'https://rubygems.org/' do
  gem 'nokogiri', '~> 1.8.4'
  gem 'cucumber'
  gem 'pry'
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'site_prism'
  gem 'page-object'
end

